server {
    listen        80;
    listen        [::]:80;
    
    # هنا يتم توجيه الخادم إلى مجلد public الخاص بـ Laravel داخل Azure
    root          /home/site/wwwroot/public;
    
    index         index.php index.html index.htm;
    server_name   localhost;

    charset utf-8;

    # توجيه جميع الطلبات إلى ملف index.php لتشغيل الـ Routing الخاص بـ Laravel
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # تخصيص صفحات الخطأ لـ Laravel
    error_page 404 /index.php;

    # إعدادات تشغيل ملفات PHP عبر مستقبل الـ FastCGI الخاص بـ Azure
    location ~ \.php$ {
        fastcgi_pass      127.0.0.1:9000;
        fastcgi_index     index.php;
        include           fastcgi_params;
        fastcgi_param     SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_read_timeout 600;
    }

    # منع الوصول إلى الملفات المخفية مثل .env أو ملفات تعديل النظام .git
    location ~ /\.(?!well-known).* {
        deny all;
    }
}